CREATE SEQUENCE CAR_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 9999999999999
     NOCYCLE
     NOCACHE;
     
     
     CREATE SEQUENCE RENTAL_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 9999999999999
     NOCYCLE
     NOCACHE;
     
     CREATE SEQUENCE CUSTOMER_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 99999
     CYCLE
     NOCACHE;
     
     CREATE SEQUENCE EQUIPMENT_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 999999
     NOCYCLE
     NOCACHE;
     
     CREATE SEQUENCE BILL_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 9999999999999
     CYCLE
     NOCACHE;
     
     CREATE SEQUENCE PAYMENT_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 9999999999999
     CYCLE
     NOCACHE;
     
     CREATE SEQUENCE STAFF_SEQ
     START WITH 1
     INCREMENT BY 1
     MINVALUE 1
     MAXVALUE 999999
     NOCYCLE
     NOCACHE;
     
     